config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  post 'owner_like', to: 'listings#owner_like', as: :owner_like

  # devise_for :users
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :homes, only: [ :index, :show, :destroy, :new, :create, :edit, :update ] do
    resources :listings, only: [:create]
  end

  resources :listings, only: [:destroy]
  root to: 'pages#home'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  geocoded_by :address

  belongs_to :owner, class_name: :User, foreign_key: :owner_id
  has_many :listing, dependent: :destroy

  validates :address, presence: true
  validates :cep, presence: true
  validates :description, presence: true
  validates :title, presence: true
  validates :city, presence: true
  validates :price, presence: true

  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :home
  belongs_to :student, class_name: :User, foreign_key: :student_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :photo, PhotoUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :homes
  has_many :listings

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
  # validates :cpf, presence: true, uniqueness: true
  # validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_home, only: [:show, :destroy, :edit, :update]

  def index
    @homes = policy_scope(Home).order(created_at: :desc)

    max_dist = params[:max_dist].to_i
    max_dist = 1_000_000 if max_dist.to_i.zero?
    location = params[:location]

    if location.nil? || location == ""
      lat = request.location.latitude.to_f
      lng = request.location.longitude.to_f
    elsif Geocoder.search(location).first.nil? == false
      lat = Geocoder.search(location).first.boundingbox[0].to_f
      lng = Geocoder.search(location).first.boundingbox[2].to_f
    end

    coordinates_hash = { lng: lng, lat: lat, home: false }
    coordinates_array = [lat, lng]

    @mark_homes = Home.where.not(latitude: nil, longitude: nil).near(coordinates_array, max_dist)

    @markers = @mark_homes.map do |home|
      {
        lng: home.longitude,
        lat: home.latitude,
        infoWindow: home.address,
        home_description: home.description,
        home_address: home.address,
        home_title: home.title,
        home_link: home_path(home),
        home_photo: home.photo.url,
        home_price: home.price,
        home: true
      }
    end

    if location.nil? || location == ""
      @markers << { lng: request.location.longitude.to_f, lat: request.location.latitude.to_f, home: false }
    elsif Geocoder.search(location).first.nil? == false
      @markers << coordinates_hash
    end
  end

  def show
  end

  def destroy
    @home.destroy
    redirect_to homes_path
  end

  def new
    @home = Home.new
    authorize @home
  end

  def create
    @home = Home.new(home_params)
    authorize @home
    @home.address = "#{@home.address} - #{@home.city}"
    @home.owner = current_user
    if @home.valid?
      @home.save
      redirect_to home_path(@home)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @home.update(home_params)
    redirect_to home_path(@home)
  end

  private

  def set_home
    @home = Home.find(params[:id])
    authorize @home
  end

  def home_params
    params.require(:home).permit(:address, :description, :title, :price, :cep, :city, :photo, :location, :max_dist)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  #  def new
  #   @listing = Listing.new
  #   authorize @listing
  # end

  def create
    @listing = Listing.new
    authorize @listing
    @listing.home_id = params[:home_id].to_i
    @listing.student_id = current_user.id
    @home = Home.find(params[:home_id])

    # student creates a listing by clicking like. The home owner will set like to TRUE when he ALSO likes
    if @home.listing.where(home_id: @home.id, student_id: current_user.id).size.zero?
      @listing.save
    else
      listing = Listing.where(home_id: @listing.home_id, student_id: @listing.student_id).first
      listing.student_like = !listing.student_like
      listing.save
    end
    redirect_to request.env["HTTP_REFERER"]
  end

  def owner_like
    @listing = Listing.find(params[:format])
    authorize @listing
    @listing.owner_like = !@listing.owner_like
    @listing.save
    redirect_to request.env["HTTP_REFERER"]
  end

  # def destroy
  #   @home.destroy
  #   redirect_to homes_path
  # end

  private

  def listing_params
    params.require(:listing).permit(:student_id, :home_id, :like)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :show, :index]
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :email, :password, :password_confirmation, :photo, :description)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :email, :password, :password_confirmation, :current_password, :photo, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    authorize @user
    @my_homes = Home.where(owner_id: @user.id)

    @my_listings = []
    Listing.all.where(student_like: true).each do |listing|
      if (listing.home.owner_id == @user.id)
        home = Home.find(listing.home_id)
        student = User.find(listing.student_id)
        @my_listings << { listing: listing, home: home, student: student, owner_like: listing.owner_like }
      end
    end

    @my_likes = []
    Listing.all.where(student_like: true).each do |listing|
      if (listing.student_id == @user.id)
        home = Home.find(listing.home_id)
        owner = User.find(listing.home.owner_id)
        @my_likes << { listing: listing, home: home, owner: owner, owner_like: listing.owner_like }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:photo, :description)
  end
end

app/views/homes/_form.html.erb
<%= simple_form_for @home do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :cep %>
  <%= f.input :city %>
  <%= f.input :address %>

  <!-- div to align both buttons  -->
  <div class="form-bottom-buttons">
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit :class => 'create-home-button' %>
  </div>
  <!-- end of div -->
<% end %>

app/views/homes/edit.html.erb
<div class="homes-edit-wrapper">

  <!-- Title -->
  <div class="homes-edit-title">
    <h3>Edit Home</h3>
  </div>
  <!-- End Title -->

  <!-- Back to Index Button -->
  <div id="homes-edit-backbutton">
  <%= link_to 'Back to home', home_path(@home) %>
  </div>
  <!-- End Button  -->

  <!-- Form -->
  <div class="homes-edit-form-container">
    <div class="homes-edit-form">
    <%= render 'form', home: @home %>
    </div>
  </div>
  <!-- End Form  -->
</div>

app/views/homes/index.html.erb
<!--     <H4>missing like button on this page/cards</H4>
-->

<div class="homes-index-wrapper">


  <!-- Middle Wrapper -->

  <div class="homes-index-middle-wrapper">
  <!-- Search Form -->
  <div class="row" class="col col-md-3">
      <div class="homes-index-search">
      <%= form_tag(homes_path, method: :get) do %>
        <%= label_tag 'Local de referência:' %>
        <%= text_field_tag :location, params[:location], :class => 'searchfield' %>
        <%= label_tag 'Distância máxima:' %>
        <%= select_tag :max_dist, options_for_select([ ["-", "-"],["5km","5km"], ["10km", "10km"], ["15km", "15km"], ["30km", "30km"]], params[:max_dist])  %>
        <%= submit_tag 'Pesquisar' %>
      <% end %>
      </div>
  </div>
  <!-- End Search Form -->
    <!-- Map Div -->
    <div class="map-wrapper">
      <div
        id="map"
        style="width: 100%;
        height: 530px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
    </div>
    <!--END MAP-->


    <!-- List Div -->
    <div class="homes-index-list-wrapper">
        <!-- Collapsible button with Owner Listing  -->
        <div class="homes-index-list-home-button">
          <button data-toggle="collapse" data-target="#demo" class="#">Meu Anúncio</button>
          <div class="homes-index-list-new-home-button">
            <%= link_to 'Novo Anúncio', new_home_path%> </p>
          </div>
        </div>
        <!-- end collapsible -->

        <!-- Div with Owner Listing  -->
        <div class="owner-home">
          <div id="demo" class="collapse">

          <!-- Owner Listing -->
          <% @homes.each do |home| %>
            <% if policy(home).owner? %>
            <p>
              <%= link_to (home_path(home)) do %>
              <%= home.title %>
              <% end %>
            </p>
            <p><i class="fas fa-map-marker-alt"></i> <%= home.address %></p>
            <p><i class="fas fa-building"></i> <%= home.description %></p>
            <img src="<%= home.photo.url %>" alt="No photos" style="width:200px;height:200px;">
            <% end %>
          <% end %>
          <!-- end owner listing -->
          </div>
        </div>
        <!-- end div with owner listing -->
      <!-- List Title -->
      <div class="homes-index-list-wrapper-title">
      <h2>Anúncios</h2>
      </div>
      <!-- End List Title -->

      <!-- List Cards -->
      <div class="homes-index-list-cards">
      <% @mark_homes.each do |home| %>
      <% if policy(home).owner? == false %>
        <ul>
<!--         <div class="homes-index-list-cards-img">
          <img src="<%= home.photo.url %>" alt="" style="width:200px;height:200px;">
        </div> -->
          <a href="" data-toggle="modal" data-target="#<%= home.owner.first_name %>"><%= home.title %></a>

        <li><i class="fas fa-map-marker-alt"></i> <%= home.address %></li>
        <li><i class="fas fa-user"></i> <%= home.owner.first_name %></li>
        <li><i class="fas fa-building"></i> <%= home.description %></li>
        <li><i class="fas fa-coins"></i> R$<%= home.price %>/mês</li>
          <div class="homes-index-list-cards-likebutton">
          <% if policy(home).logged_in?%>
            <% if policy(home).liked? == false%>
                <%= link_to 'like', home_listings_path(home_id: home),
                    method: 'post', :class => 'btn btn-success like-button', :id => home.id, remote: true %>
            <% else %>
              <%= link_to 'dislike', home_listings_path(home_id: home),
                    method: 'post', :class => 'btn btn-warning like-button', :id => home.id, remote: true %>
            <% end %>
          <% else %>
              <%= link_to 'like', home_listings_path(home_id: home),
                  method: 'post', :class => 'btn btn-success like-button'%>
          <% end %>
          </div>
        </ul>
        <!-- Modal begin -->
        <div id="<%= home.owner.first_name %>" class="modal fade" role="dialog">
          <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><%= home.title %> <%= home.owner.last_name %></h4>
              </div>
              <div class="modal-body">
                <%= cl_image_tag home.photo, height: 300, width: 300, crop: :thumb, gravity: :face %>

                <li><i class="fas fa-map-marker-alt"></i> <%= home.address %></li>
                <li><i class="fas fa-user"></i> <%= home.owner.first_name %></li>
                <li><i class="fas fa-building"></i> <%= home.description %></li>
                <li><i class="fas fa-coins"></i> R$<%= home.price %>/mês</li>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>

          </div>
        </div>
        <!-- Modal end -->

        <% end %>
      <% end %>
      </div>
      <!-- End List Cards -->

      <!-- Modal Homes  -->


    </div>
  </div>
  <!-- Footer -->
<footer class="page-footer font-small">
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2019 Copyright:
    <a href="https://www.senhorbarriga.com/"> SenhorBarriga.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- End Footer -->
</div>

app/views/homes/new.html.erb
<div class="homes-new-wrapper">

  <!-- Title -->
  <div class="homes-new-title">
    <h3>New Home</h3>
  </div>
  <!-- End Title -->

  <!-- Back to Index Button  -->
  <div id="homes-new-backbutton">
  <!-- <%= link_to 'Back to index', homes_path %> -->
  </div>
  <!-- End Button -->

  <!-- Form -->
  <div class="homes-new-form-container">
    <div class="homes-new-form">
    <%= render 'form', home: @home %>
    </div>
  </div>
  <!-- End Form -->
</div>

app/views/homes/show.html.erb
<div class="homes-show-wrapper">



  <div class="homes-show-card-wrapper">

    <div class="homes-show-card">
      <div> <!-- div pictures box -->
        <div>
          <%= cl_image_tag @home.photo, height: 300, width: 400 %>
        </div>
      </div>

      <!-- Card Info -->
      <div class="homes-show-card-info"> <!-- div home description -->

       <ul>
        <li>  <p> <%= @home.title %> </p> </li>
        <li><i class="fas fa-building"></i> <%= @home.description %></i></li> <!-- name -->
        <li><i class="fas fa-map-marker-alt"></i> </li> <!-- description -->
        <li><i class="fas fa-user"></i> <%= @home.owner.first_name %></li> <!-- name -->
        <li><i class="fas fa-phone"></i> <%= @home.owner.phone_number %></li> <!-- description -->
      </ul>
    </div>

    <div> <!-- div like button -->
      <% if policy(@home).owner? == false %>
      <% if policy(@home).logged_in?%>
      <% if policy(@home).liked? == false%>
      <%= link_to 'like', home_listings_path(home_id: @home),
      method: 'post', :class => 'btn btn-success like-button', :id => @home.id, remote: true %>
      <% else %>
      <%= link_to 'dislike', home_listings_path(home_id: @home),
      method: 'post', :class => 'btn btn-warning like-button', :id => @home.id, remote: true %>
      <% end %>
      <% else %>
      <%= link_to 'like', home_listings_path(home_id: @home),
      method: 'post', :class => 'btn btn-success like-button'%>
      <% end %>
      <% end %>
    </div>

    <div class="homes-show-card-edit-button">
    <%  if policy(@home).edit? %>
    <%= link_to 'edit home', edit_home_path(@home) %>
    <% end %>
    </div>

    <div class="homes-show-card-delete-button">
      <% if policy(@home).destroy? %>
      <%=  link_to 'delete home', home_path(@home),
      method: :delete,
      data: { confirm: "Are you sure?"} %>
      <% end %>
    </div>
  </div>
  <!-- End Card Info -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Senhor Barriga</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<body>

  <!-- Upper Home (Banner + Modal Buttons) -->

  <div class="upper-wrapper">

    <!-- Banner  -->
    <div class="banner">


      <!-- Animation Home -->
      <h1>Está
        <span
        class="txt-rotate"
        data-period="2000"
        data-rotate='[ "procurando um apartamento?", "buscando alguém para morar com você?", "no lugar certo!" ]'></span>
      </h1>
      <!-- End Animation Home -->

    </div>

    <!-- Home Buttons -->
    <div class="modal-wrapper">
      <div class="modal-buttons">
        <!-- Button trigger modal owner -->
        <%= link_to new_home_path do %>
        <button type="button" class="buttons-home">
          Quero oferecer vagas
        </button>
        <% end %>
        <!-- Button trigger modal user -->
        <%= link_to homes_path do %>
        <button type="button" class="buttons-home">
          Quero encontrar vagas
        </button>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- End Home Buttons -->

<!-- Start Bottom Seccion -->
<div class="bottom-wrapper">
  <!-- User Testimonials -->
  <div class="row text-center">
    <div class="col-sm-6 col-md-4">
      <div class="testimonial-box">
        <img src="https://images.pexels.com/photos/206615/pexels-photo-206615.jpeg?w=940&h=650&auto=compress&cs=tinysrgb" class="img-responsive" alt="" width="90">
        <div class="ratings-icons">
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
        </div>
        <h4>Joana Gomes</h4>
        <p>O Senhor Barriga me ajudou a encontrar as melhores colegas de quarto que eu poderia! Já estava cansada de procurar mas sempre era uma dor de cabeça. Em poucos dias meu anúncio teve várias curtidas e pude escolher com quem vou morar.</p>

      </div>
    </div> <!-- End Col -->

    <div class="col-sm-6 col-md-4">
      <div class="testimonial-box">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjtlV77iiy77jZPBi4tCAF4OhW3pLmzykfty5xHq5kcl6YFWtIfA" class="img-responsive" alt="" width="90">
        <div class="ratings-icons">
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
        </div>
        <h4>Edson Oliveira</h4>
        <p>Estava buscando um quarto perto da faculdade e o Senhor Barriga me ajudou a encontrar a melhor opção, e o melhor de tudo, dentro do meu orçamento!</p>

      </div>
    </div> <!-- End Col -->

    <div class="col-sm-6 col-md-4">
      <div class="testimonial-box">
        <img src="https://images.pexels.com/photos/478544/pexels-photo-478544.jpeg?w=940&h=650&auto=compress&cs=tinysrgb" class="img-responsive" alt="" width="90">
        <div class="ratings-icons">
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
        </div>
        <h4>Maria de Lourdes</h4>
        <p>Foi super legal poder escolher alguém entre as pessoas que curtiram meu anúncio. Acredito que vou me dar muito bem com minha nova colega de apartamento.</p>

      </div>
    </div> <!-- End Col -->
    <!-- End User Testimonials -->

  </div>
</div>
<!-- Footer -->
<footer class="page-footer font-small">
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2019 Copyright:
    <a href="https:www.senhorbarriga.com/"> SenhorBarriga.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- End Footer -->
</body>

app/views/shared/_cards.html.erb
<ul>
  <li> </li>
  <li> </li>
</ul>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->


  <%= link_to homes_path, class: "navbar-wagon-brand" do %>
    <i class="fas fa-home"></i>
  <% end %>
  <%= image_tag ("logo.png"), style: 'width:250px; height: 66px;' %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right ">

    <% if user_signed_in? %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to users_show_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
<!--   <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div> -->
</div>

app/views/users/show.html.erb
<div class="users-show-title">
  <h2>User Profile</h2>
</div>

<div class="container">
  <!-- User Information Div -->
  <div class="users-show-info"> <!-- this is the user info div -->
    <!-- <h4> User Information</h4> -->
    <p><i class="fas fa-envelope"></i> &nbsp;<%= @user.email%></p>
    <p><i class="fas fa-user"></i> &nbsp;<%= @user.first_name %>
      <%= @user.last_name  %></p>
      <p><i class="fas fa-phone"></i> &nbsp;<%= @user.phone_number %></p>
      <%= link_to 'edit', edit_user_registration_path(@user) %>
    </div>
    <!-- End User Information Div -->

    <!-- User Home Div  -->
    <div class="users-show-home"> <!-- this is the apartment div -->
      <!-- User Home Title -->
      <div class="users-show-home-title">
        <h4>My home</h4>
      </div>
      <!-- Ends User Home Title -->
      <% if policy(current_user).homes_not_zero?(@my_homes) %>
      <p><%= @my_homes.first.title %></p>
      <p><%= @my_homes.first.address %></p>
      <p><%= @my_homes.first.description %></p>
      <% end %>
      <% if policy(current_user).homes_not_zero?(@my_homes) %>
      <% @my_homes.each do |home| %>
      <%= link_to home_path(home) do %>
      <p><%= home.title %></p>
      <% end %>
      <% end %>
      <% end %>
    </div>
    <!-- End User Home Div -->

    <!-- User Likes Div -->
    <div class="users-show-likes"> <!-- this is the likes div -->
      <!-- User Likes Title  -->
      <div class="users-show-likes-title">
        <h3> List of interested users </h3>
      </div>
      <!-- Ends User Likes Title -->
      <% @my_listings.each do |listing| %>
      <p>The user <strong><a href="" data-toggle="modal" data-target="#myModal"><%= listing[:student].first_name %></a></strong>
        liked your
      <%= link_to home_path(listing[:home]) do %>
      <%= listing[:home].title %>
      <% if policy(listing[:listing]).liked_as_owner? %>
      <%= link_to 'dislike', owner_like_path(listing[:listing]), method: :post, :class => 'btn btn-warning like-button', remote: true %>
      <% else %>
      <%= link_to 'like', owner_like_path(listing[:listing]), method: :post, :class => 'btn btn-success like-button', remote: true %>
      <% end %> listing

      <!-- student modal -->
      <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title"><%= listing[:student].first_name %> <%= listing[:student].last_name %></h4>
            </div>
            <div class="modal-body">
              <%= cl_image_tag listing[:student].photo, height: 300, width: 300, crop: :thumb, gravity: :face %>
              <p>Some text in the modal.</p>
              <p><strong>Email: </strong><%= listing[:student].email %></p>
              <p><strong>Phone: </strong><%= listing[:student].phone_number %></p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>

        </div>
      </div>
      <% end %>
      <% end %></p>

      <!-- end student modal -->
    </div>
    <!-- End User Likes Div -->


    <!-- User Matches Div -->
    <div class="users-shows-match">
      <!-- User Matches Title -->
      <div class="users-show-match-title">
        <h3>My likes</h3>
      </div>
      <!-- Ends User Matches Title -->
      <% @my_likes.each do |listing| %>
      <div class="users-show-match-card">
      <p> You liked
        <%= link_to home_path(listing[:home]) do %>
        <%= listing[:home].title %>
        <% end %>
        <% if listing[:owner_like] == true %>
        and <strong><a href="" data-toggle="modal" data-target="#ownerModal"><%= listing[:owner].first_name %></a></strong> liked you back. It's a <i class="fas fa-heart"></i> match!
        <% end %>
      </p>

        <!-- owner modal -->
        <div id="ownerModal" class="modal fade" role="dialog">
          <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><%= listing[:owner].first_name %> <%= listing[:owner].last_name %></h4>
              </div>
              <div class="modal-body">
                <%= cl_image_tag listing[:owner].photo, height: 300, width: 300, crop: :thumb, gravity: :face %>
                <p>Some text in the modal.</p>
                <p><strong>Email: </strong><%= listing[:owner].email %></p>
                <p><strong>Phone: </strong><%= listing[:owner].phone_number %></p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>

          </div>
        </div>
        <!-- end owner modal -->

      <% end %>
      </div>
    </div>
    <!-- End User Matches Div -->

  </div>